Allow configurable Shards & Replicas on Contacts Index
nyaruka/rp-indexer pull request #54
Opened 2022-08-08 13:37 UTC by tybritten

2022-10-10 20:34 UTC, rowanseymour requested changes

2022-10-10 20:34 UTC, rowanseymour commented on indexers/contacts.go
> +	"time"
gofmt should have `time` up above...

2022-10-10 20:34 UTC, rowanseymour commented on indexers/contacts.go
> +		_ = json.Unmarshal(contactsSettingsFile, &contactsSettings)
should handle this error

2022-10-10 21:10 UTC, tybritten commented on indexers/contacts.go
> +	"time"
it kept moving it to the bottom 🤷🏻

2022-10-11 21:36 UTC, rowanseymour commented on indexers/contacts.go
> +		_ = json.Unmarshal(contactsSettingsFile, &contactsSettings)
ah just noticed this is unmarshaling an embedded file so shouldn't ever error - anyways I'll merge and tweak to use `jsonx.MustUnmarshal`

2022-10-11 21:36 UTC, merged